### ISSUE TITLE
Metrics involving programmers

### ISSUE THREAD

**Issue by Brayden-Arthur** [Brayden-Arthur/SENG-371-Project-1#1]
I need another tool to measure when a programmer is working on a project

Just found gitinspector, this might be just what I need

**Comment by gregnr** [comment]
Take a look at [GitStats](http://gitstats.sourceforge.net/). It can do:
- General statistics: total files, lines, commits, authors.
- Activity: commits by hour of day, day of week, hour of week, month of year, year and month, and year.
- Authors: list of authors (name, commits (%), first commit date, last commit date, age), author of month, author of year.
- Files: file count by date, extensions
- Lines: Lines of Code by date
